{
    'name' : 'Inventory and Stock Warehouse Report',
    'author': "Edge Technologies",
    'version' : '13.0.1.1',
    'live_test_url':'https://youtu.be/69n5iyMfHYg',
    "images":["static/description/main_screenshot.png"],
    'summary' : 'Warehouse aging Report Inventory Report Warehouse Stock Report product stock report warehouse product detail report product balance report product aging report warehouse stock aging report inventory valuation report stock card report inventory aging report',
    'description' : """
        Inventory and Stock Warehouse Report
    """,
    'depends' : ['base','sale_management','stock','purchase'],
    "license" : "OPL-1",
    'data': [
            'security/group_warehouse_report.xml',
            'views/inherit_warehouse_report.xml',
            'wizard/warehouse_stock_aging_report_wiz_view.xml',
            'report/warehouse_stock_aging_report_action.xml',
            'report/warehouse_stock_aging_report_temp.xml',
            'wizard/warehouse_stock_aging_mmt_report_wiz_view.xml',
            'report/warehouse_stock_aging_mmt_report_temp.xml',
            'report/warehouse_stock_aging_mmt_report_action.xml',
            'wizard/warehouse_stock_valution_report_wiz_view.xml',
            'report/warehouse_stock_valution_report_temp.xml',
            'report/warehouse_stock_valution_report_action.xml',
            'wizard/warehouse_stock_status_report_wiz_view.xml',
            'report/warehouse_stock_status_report_temp.xml',
            'report/warehouse_stock_status_report_action.xml',
            'wizard/warehouse_stock_location_transfer_report_wiz_view.xml',
            'report/warehouse_stock_location_transfer_report_temp.xml',
            'report/warehouse_stock_location_transfer_report_action.xml',
            'wizard/warehouse_stock_movement_report_wiz_view.xml',
            'report/warehouse_stock_movement_report_temp.xml',
            'report/warehouse_stock_movement_report_action.xml',
            ],
    'qweb' : [],
    'demo' : [],
    'installable' : True,
    'auto_install' : False,
    'price': 20,
    'currency': "EUR",
    'category' : 'Warehouse',
}
